### ISSUE TITLE
minSdkVersion 21 now? Sure?

### ISSUE THREAD

**Issue by tomsun3** [doorbell/android-sdk#25]
Hi, just with the latest updates you switched your libs minSdkVersion from at most 16 (mine is 16) to 21. I do not think this is needed for this small changes, but has a high impact on your customers / people using your service/library.

I can't use the newest version (0.4.5) of your library as the minSdkVersion is higher than the minSdkVersion of my app (which is 16). I am pretty sure you can go back down to at most 16 as minSdkVersion. Otherwise, I can't use your (current) library and service anymore as my app also supports older devices and I can't do that - going up to minSdkVersion 21. And I think you also should not do that.

Have a great day,
Thomas

**Comment by manavo** [comment]
Hi @thomasmo3, thanks for flagging this!

I think it can be bumped back down a bit, but 16 makes it trickier. With moving from the Apache HTTP client to HttpsUrlConnection, there will be trouble with older devices that don't already support TLS1.2. But I think it needs to be minSdkVersion of 19 to not have trouble with the TLS1.2 requirement. And even 19 is questionable, since 4.4.2 is the minimum version where it will all work without issue.

The best we can do is prompt the user to patch their device using https://developer.android.com/training/articles/security-gms-provider, which is only half a solution. If they update it (manual process for the user), then it _should_ work. If they don't, there will be SSL errors and the feedback won't be submitted.

I've committed the change above to support down to SDK 16, with the check/prompt to update Play Services if needed. Are you able to test this directly with what's committed but not released, to see if it works for you? (this can't really be tested on an emulator)

**Comment by tomsun3** [comment]
Hi @manavo,

thanks a lot for your quick and detailed response!

I understand the technical issue - maybe it would be productive to show an AlertDialog if no connection can be made (due to an old Android version / low API version) and instead provide an old-school email procedure to contact the developer? That would be great as you would not have to set the minSdk that high.

I would have to exclude ~50users by following your sdk upgrade with your newest update - can't really do that right now :/

Could you please provide some tips on how to test that commit? Tried to download it and import as module, but that didn't work out. Can I do that using gradle/Jitpack.

Thanks,
Thomas

**Comment by manavo** [comment]
Hi @thomasmo3,

With Jitpack you should be able to do something like this? https://stackoverflow.com/a/32682034/349012 (I haven't tested it, but looks fairly straightforward!)

I think the solution might be to expose some functions where you can check for compatibility, and then decide what the best option would be. That would give you (and other users) max flexibility.

So if you could run something like:

```java
Doorbell d = new Doorbell(this, 1, "private_key");
if (d.isFullyCompatible()) {
  d.show();
} else {
  // Open mail app, pre-populated with some values like "To" and "Subject"
}
```

(the above doesn't exist yet, it's just an example)

I'm guessing that would work for you?

Thanks,
Phil

**Comment by tomsun3** [comment]
Hi @manavo,

thanks a lot for your hint - that worked like a charm.

I have no old test device, but tested this version of the library (your latest master commit) with API 28 Android and in emulator with newest API 31. There seems to be no problem - everything works great as expected. Unfortunately, I can't provide an older device.

Yes! I think, your suggested solution using a compability function to check for a boolean etc. and handle separately on older devices would be the way to go - that's so much better, since you do not exclude/prevent apps supporting devices from old APIs using your library and service!

Thanks for your help, looking forward to the upcoming update(?)

All the best,
Thomas

**Comment by manavo** [comment]
Hi @thomasmo3,

All set with this, and going to push a new release now.

Not added to the docs yet, but you'll be able to do this:

```java
            if (doorbellInstance.isFullySupported()) {
                doorbellInstance.show();
            } else {
                // Prompt to open mail client
            }
```

Thanks for helping with this!

**Comment by manavo** [comment]
`0.4.6` is just tagged and will be available through Maven soon. I'll close this now, but if you run into any issues with this let me know!

**Comment by manavo** [comment]
`0.4.7` actually, mis-tagged `0.4.6`

**Comment by tomsun3** [comment]
Works great, thank you! @manavo
